[bin] bak & unbak have improved error handling now

diff --git a/bin/bak b/bin/bak
--- a/bin/bak
+++ b/bin/bak
@@ -19,8 +19,13 @@ if [ "$1" == "-c" ] ; then
 	copy=true
 fi
 path=$(echo "$1" | sed -e 's/\/$//')
-if [ $copy == true ]; then
-	cp -r $path $path.bak
+if [ -e $path ]; then
+	if [ $copy == true ]; then
+		cp -r $path $path.bak
+	else
+		mv $path $path.bak
+	fi
 else
-	mv $path $path.bak
+	echo "⚠️  path not found: $path"
+	exit 64 # EX_USAGE (64)	   The command was used	incorrectly
 fi
diff --git a/bin/unbak b/bin/unbak
--- a/bin/unbak
+++ b/bin/unbak
@@ -14,8 +14,13 @@ if [ "$1" == "-c" ] ; then
 fi
 
 path=$(echo $1 | sed -e "s/.bak$//")
-if [ "$copy" == true ]; then
-	cp -r $path.bak $path
+if [ -e $path.bak ]; then
+	if [ "$copy" == true ]; then
+		cp -r $path.bak $path
+	else
+		mv $path.bak $path
+	fi
 else
-	mv $path.bak $path
+	echo "⚠️  path not found: $path.bak"
+	exit 64 # EX_USAGE (64)	   The command was used	incorrectly
 fi
