improved html2pdf and added clu docs

diff --git a/bin/html2pdf b/bin/html2pdf
--- a/bin/html2pdf
+++ b/bin/html2pdf
@@ -1,9 +1,60 @@
 #!/bin/sh
 
-tempfile=$(mktemp /tmp/html2pdf.XXXXXX)
+
 
 # must end with .html or chrome will treat it
 # as if it were plain text
+#
+#
+
+function usage {
+    echo "Usage: html2pdf [-i input_file.html | -o output_file.pdf | -h]"
+    echo "    -h Display this help message"
+    echo "    -i specify the path to a file to convert"
+    echo "    -o specify the name/path to the output file"
+    echo ""
+    echo "    If you don't specify an input file STDIN will be used."
+    echo "    If you don't specify an output file ./output.pdf will be created."
+    echo "    If your file doesn't end in .html Chrome will treat it as text"
+    exit 0
+}
+
+# Detect the platform (similar to $OSTYPE)
+OS="`uname`"
+case $OS in
+  'Linux')
+    OS='Linux'
+    alias ls='ls --color=auto'
+    ;;
+  'FreeBSD')
+    OS='FreeBSD'
+    alias ls='ls -G'
+    ;;
+  'WindowsNT')
+    OS='Windows'
+    ;;
+  'Darwin')
+    OS='Mac'
+    ;;
+  'SunOS')
+    OS='Solaris'
+    ;;
+  'AIX') ;;
+  *) ;;
+esac
+
+if [ "$OS" == "Mac" ]; then
+  #What the Ever Living F#*K ?!
+  OS="Darwin";
+fi
+
+if [ "$OS" != "Darwin" ] && [ "$OS" != "FreeBSD" ] && [ "$OS" != "Linux" ]; then
+	echo "I only know how to invoke Chrome on MacOS, Linux, and FreeBSD";
+	echo "Sorry."
+	echo "You can edit the invocation code at the end of this if you know"
+	echo "how to invoke it from the command line on $OS"
+	exit 1;
+fi
 
 while getopts ":ioh" opt; do
   case ${opt} in
@@ -14,14 +65,7 @@ while getopts ":ioh" opt; do
       OUTPUT=$OPTARG
       ;;
     h )
-      echo "Usage: html2pdf [-i input_file.html | -o output_file.pdf | -h]"
-      echo "    -h Display this help message"
-      echo "    -i specify the path to a file to convert"
-      echo "    -o specify the name/path to the output file"
-      echo ""
-      echo "    If you don't specify an input file STDIN will be used."
-      echo "    If you don't specify an output file ./output.pdf will be created."
-      exit 0
+      usage
       ;;
     \? )
       echo "Invalid option $OPTARG" 1>&2
@@ -34,15 +78,39 @@ if [ "$INPUT" == "" ]; then
   INPUT="-"
 fi
 
+
+
+tempfile=$(mktemp /tmp/html2pdf.XXXXXX)
 cat $INPUT > $tempfile
 mv $tempfile $tempfile".html"
 # on linux everything before --headless can be replaced with just
 # chrome
-/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome \
-  --headless \
-  --disable-gpu \
-  --no-margins \
-  --print-to-pdf $tempfile".html" 2>/dev/null
+if [ "$OS" == "Darwin" ]; then
+  if ! test -e /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome ; then
+    echo "I couldn't find Chrome. I expected to find it here:"
+    echo "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
+    exit 1;
+  fi
+
+  /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome \
+    --headless \
+    --disable-gpu \
+    --no-margins \
+    --print-to-pdf $tempfile".html" 2>/dev/null
+else
+  command -v chrome > /dev/null
+  if [ $? -ne 0 ]; then
+    echo "I couldn't find the chrome executable."
+    echo "I expected it to be in your \$PATH"
+    exit 1
+  fi
+
+  chrome
+    --headless \
+    --disable-gpu \
+    --no-margins \
+    --print-to-pdf $tempfile".html" 2>/dev/null
+fi
 
 rm $tempfile".html"
 
